let map = {
    "MODE": "tdm",
    "ISSIEGE": true, 
    "serverName": "Boss Rush",//siege
    "TEAM_AMOUNT": 1,
    "MODE": "tdm",
    "WIDTH": 8000,
    "HEIGHT": 8000,
    "X_GRID": 30,
    "Y_GRID": 30,
    "MAX_FOOD": 20,
    "MAX_NEST_FOOD": 10,
    "MAX_CRASHERS": 30,
    "MAX_SANCS": 3,
    "ROOM_SETUP": [                                                                                     //mid
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","bas1","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","bas1","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"], //mid
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","bas1","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"], //what
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","bas1","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ["myboss","myboss","myboss","myboss","myboss","myboss","myboss","myboss","bas2","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm"],
    ],
    "BOTS": 15,
    "BORDER_FORCE": 0.025,
}
map