let map = {//normal map
    "MODE": "tdm",
    "serverName": "CUSTOOOOOOOOOOOMMMMMMMMMMMMMM",
    "TEAM_AMOUNT": 2,
    "MODE": "tdm",
    "WIDTH": 8000,
    "HEIGHT": 8000,
    "X_GRID": 30,
    "Y_GRID": 30,
    "MAX_FOOD": 225,
    "MAX_NEST_FOOD": 50,
    "MAX_CRASHERS": 20,
    "MAX_SANCS": 3,
    "TIME_BETWEEN_SANCS": 9000,
    "ROOM_SETUP": [                                                                                     //mid
    ["n_b1","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","nest","nest","nest","nest","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","norm","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","norm","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","nest","norm","norm","norm","norm","nest","nest","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","norm","nest","nest","nest","nest","nest","nest","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","boss","boss","boss","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","boss","boss","boss","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","n_b2"], //mid
    ["n_b1","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","boss","boss","boss","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","n_b2"], //what
    ["n_b1","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","norm","norm","norm","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","nest","nest","nest","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","nest","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","nest","nest","nest","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","nest","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","nest","nest","nest","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","nest","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","nest","nest","nest","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","nest","nest","nest","norm","norm","norm","n_b2"],
    ["n_b1","norm","nest","nest","nest","nest","nest","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","norm","nest","nest","nest","nest","nest","norm","norm","norm","n_b2"],
    ],
    "BOTS": 4,
    "SKILL_BOOST": 5,
    "BORDER_FORCE": 0.0025,
    "DAMAGE_CONSTANT": 0.75,//0.75
    "KNOCKBACK_CONSTANT": 1.8,
    "MAX_SKILL": 9,
    "SOFT_MAX_SKILL": 0.59,
    "REGEN_MULTIPLIER": 0.45,
    //"OUTSIDE_ROOM_DAMAGE": 0.1,
    "LEVEL_ZERO_UPGRADES": false,
    //"SKILL_CAP": 60,
    "SKILL_SOFT_CAP": 0,
    //"SKILL_CHEAT_CAP": 60,
    "SKILL_LEAK": 0,
    "STEALTH": 4,
    "MIN_SPEED": 0.001,
    "MIN_DAMAGE": 0,
    "MAX_FOOD": 400,
    "BOSS_SPAWN_TIMER": 60,//50
    "SHINY_CHANCE": 0.0025,  //joke
    "TIER_1": 15,
    "TIER_2": 30,
    "TIER_3": 45,
    "TIER_4": 60,
    //"gameSpeed": 10
}
map